<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE register [
	<!ELEMENT register (item)+>
	<!ELEMENT item (id, name, abbr?)>
	<!ELEMENT id (#PCDATA)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT abbr (#PCDATA)>
]>
<register>
	<item>
		<id>1</id>
		<name>amtssprachlich</name>
		<abbr>amtsspr.</abbr>
	</item>
	<item>
		<id>2</id>
		<name>bildlich</name>
		<abbr>bildl.</abbr>
	</item>
	<item>
		<id>3</id>
		<name>bildungssprachlich</name>
		<abbr>bildungsspr.</abbr>
	</item>
	<item>
		<id>4</id>
		<name>derb</name>
	</item>
	<item>
		<id>5</id>
		<name>gehoben</name>
		<abbr>geh.</abbr>
	</item>
	<item>
		<id>6</id>
		<name>ironisch</name>
		<abbr>iron.</abbr>
	</item>
	<item>
		<id>7</id>
		<name>literarisch</name>
		<abbr>lit.</abbr>
	</item>
	<item>
		<id>8</id>
		<name>rechtssprachlich</name>
		<abbr>rechtsspr.</abbr>
	</item>
	<item>
		<id>9</id>
		<name>scherzhaft</name>
		<abbr>scherzh.</abbr>
	</item>
	<item>
		<id>10</id>
		<name>schriftsprachlich</name>
		<abbr>schriftspr.</abbr>
	</item>
	<item>
		<id>11</id>
		<name>skatologisch</name>
		<abbr>skatolog.</abbr>
	</item>
	<item>
		<id>12</id>
		<name>spöttisch</name>
		<abbr>spött.</abbr>
	</item>
	<item>
		<id>13</id>
		<name>standardsprachlich</name>
		<abbr>standardspr.</abbr>
	</item>
	<item>
		<id>14</id>
		<name>übertragen</name>
		<abbr>übertr.</abbr>
	</item>
	<item>
		<id>15</id>
		<name>umgangssprachlich</name>
		<abbr>ugs.</abbr>
	</item>
	<item>
		<id>16</id>
		<name>ungebräuchlich</name>
		<abbr>ungebr.</abbr>
	</item>
	<item>
		<id>17</id>
		<name>verächtlich</name>
		<abbr>verächtl.</abbr>
	</item>
	<item>
		<id>18</id>
		<name>veraltend</name>
	</item>
	<item>
		<id>19</id>
		<name>veraltet</name>
	</item>
	<item>
		<id>20</id>
		<name>verhüllend</name>
		<abbr>verhüll.</abbr>
	</item>
</register>
