<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE regiolekte [
	<!ELEMENT regiolekte (item)+>
	<!ELEMENT item (id, name, abbr?)>
	<!ELEMENT id (#PCDATA)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT abbr (#PCDATA)>
]>
<regiolekte>
	<item>
		<id>1</id>
		<name>alemannisch</name>
		<abbr>alem.</abbr>
	</item>
	<item>
		<id>2</id>
		<name>badisch</name>
		<abbr>bad.</abbr>
	</item>
	<item>
		<id>3</id>
		<name>bairisch</name>
		<abbr>bair.</abbr>
	</item>
	<item>
		<id>4</id>
		<name>berlinisch</name>
		<abbr>berlin.</abbr>
	</item>
	<item>
		<id>5</id>
		<name>böhmisch</name>
		<abbr>böhm.</abbr>
	</item>
	<item>
		<id>6</id>
		<name>brandenburgisch</name>
		<abbr>brand.</abbr>
	</item>
	<item>
		<id>7</id>
		<name>elsässisch</name>
		<abbr>els.</abbr>
	</item>
	<item>
		<id>8</id>
		<name>fränkisch</name>
		<abbr>frk.</abbr>
	</item>
	<item>
		<id>9</id>
		<name>hessisch</name>
		<abbr>hess.</abbr>
	</item>
	<item>
		<id>10</id>
		<name>hochdeutsch</name>
		<abbr>hd.</abbr>
	</item>
	<item>
		<id>11</id>
		<name>holsteinisch</name>
		<abbr>holst.</abbr>
	</item>
	<item>
		<id>12</id>
		<name>inseldeutsch</name>
		<abbr>inseld.</abbr>
	</item>
	<item>
		<id>13</id>
		<name>landschaftlich</name>
		<abbr>landschaftl.</abbr>
	</item>
	<item>
		<id>14</id>
		<name>lothringisch</name>
		<abbr>lothr.</abbr>
	</item>
	<item>
		<id>15</id>
		<name>luxemburgisch</name>
		<abbr>lux.</abbr>
	</item>
	<item>
		<id>16</id>
		<name>mährisch</name>
		<abbr>mähr.</abbr>
	</item>
	<item>
		<id>17</id>
		<name>mecklenburgisch</name>
		<abbr>meckl.</abbr>
	</item>
	<item>
		<id>18</id>
		<name>mitteldeutsch</name>
		<abbr>md.</abbr>
	</item>
	<item>
		<id>19</id>
		<name>mittelfränkisch</name>
		<abbr>mfrk.</abbr>
	</item>
	<item>
		<id>20</id>
		<name>moselfränkisch</name>
		<abbr>mosfrk.</abbr>
	</item>
	<item>
		<id>21</id>
		<name>mundartlich</name>
		<abbr>mdal.</abbr>
	</item>
	<item>
		<id>22</id>
		<name>niederdeutsch</name>
		<abbr>nd.</abbr>
	</item>
	<item>
		<id>23</id>
		<name>niedersächsisch</name>
		<abbr>ns.</abbr>
	</item>
	<item>
		<id>24</id>
		<name>norddeutsch</name>
		<abbr>nordd.</abbr>
	</item>
	<item>
		<id>25</id>
		<name>nordostdeutsch</name>
		<abbr>nordostd.</abbr>
	</item>
	<item>
		<id>26</id>
		<name>nordwestdeutsch</name>
		<abbr>nordwestd.</abbr>
	</item>
	<item>
		<id>27</id>
		<name>oberdeutsch</name>
		<abbr>obd.</abbr>
	</item>
	<item>
		<id>28</id>
		<name>oberfränkisch</name>
		<abbr>obfrk.</abbr>
	</item>
	<item>
		<id>29</id>
		<name>obersächsisch</name>
		<abbr>obs.</abbr>
	</item>
	<item>
		<id>30</id>
		<name>österreichisch</name>
		<abbr>öst.</abbr>
	</item>
	<item>
		<id>31</id>
		<name>ostfränkisch</name>
		<abbr>ofrk.</abbr>
	</item>
	<item>
		<id>32</id>
		<name>ostmitteldeutsch</name>
		<abbr>omd.</abbr>
	</item>
	<item>
		<id>33</id>
		<name>ostoberdeutsch</name>
		<abbr>ostobd.</abbr>
	</item>
	<item>
		<id>34</id>
		<name>ostpreußisch</name>
		<abbr>ostpreuß.</abbr>
	</item>
	<item>
		<id>35</id>
		<name>pfälzisch</name>
		<abbr>pfälz.</abbr>
	</item>
	<item>
		<id>36</id>
		<name>pommerisch</name>
		<abbr>pomm.</abbr>
	</item>
	<item>
		<id>37</id>
		<name>preußisch</name>
		<abbr>preuß.</abbr>
	</item>
	<item>
		<id>38</id>
		<name>rheinfränkisch</name>
		<abbr>rhfrk.</abbr>
	</item>
	<item>
		<id>39</id>
		<name>rheinisch</name>
		<abbr>rhein.</abbr>
	</item>
	<item>
		<id>40</id>
		<name>ripuarisch</name>
		<abbr>rip.</abbr>
	</item>
	<item>
		<id>41</id>
		<name>sächsisch</name>
		<abbr>sächs.</abbr>
	</item>
	<item>
		<id>42</id>
		<name>schlesisch</name>
		<abbr>schles.</abbr>
	</item>
	<item>
		<id>43</id>
		<name>schleswigisch</name>
		<abbr>schlesw.</abbr>
	</item>
	<item>
		<id>44</id>
		<name>schwäbisch</name>
		<abbr>schwäb.</abbr>
	</item>
	<item>
		<id>45</id>
		<name>schweizerisch</name>
		<abbr>schweiz.</abbr>
	</item>
	<item>
		<id>46</id>
		<name>siebenbürgisch</name>
		<abbr>siebenb.</abbr>
	</item>
	<item>
		<id>47</id>
		<name>süddeutsch</name>
		<abbr>südd.</abbr>
	</item>
	<item>
		<id>48</id>
		<name>südwestdeutsch</name>
		<abbr>südwestd.</abbr>
	</item>
	<item>
		<id>49</id>
		<name>thüringisch</name>
		<abbr>thür.</abbr>
	</item>
	<item>
		<id>50</id>
		<name>westfälisch</name>
		<abbr>westf.</abbr>
	</item>
	<item>
		<id>51</id>
		<name>westmitteldeutsch</name>
		<abbr>wmd.</abbr>
	</item>
	<item>
		<id>52</id>
		<name>westoberdeutsch</name>
		<abbr>westobd.</abbr>
	</item>
	<item>
		<id>53</id>
		<name>wienerisch</name>
		<abbr>wiener.</abbr>
	</item>
	<item>
		<id>54</id>
		<name>württembergisch</name>
		<abbr>württ.</abbr>
	</item>
</regiolekte>
