<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE sprachen [
	<!ELEMENT sprachen (item)+>
	<!ELEMENT item (id, name, abbr?)>
	<!ELEMENT id (#PCDATA)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT abbr (#PCDATA)>
]>
<sprachen>
	<item>
		<id>1</id>
		<name>albanisch</name>
		<abbr>alban.</abbr>
	</item>
	<item>
		<id>2</id>
		<name>altdänisch</name>
		<abbr>adaen.</abbr>
	</item>
	<item>
		<id>3</id>
		<name>altenglisch</name>
		<abbr>aengl.</abbr>
	</item>
	<item>
		<id>4</id>
		<name>altfranzösisch</name>
		<abbr>afrz.</abbr>
	</item>
	<item>
		<id>5</id>
		<name>altfriesisch</name>
		<abbr>afries.</abbr>
	</item>
	<item>
		<id>6</id>
		<name>altgermanisch</name>
		<abbr>agerm.</abbr>
	</item>
	<item>
		<id>7</id>
		<name>altgriechisch</name>
		<abbr>agriech.</abbr>
	</item>
	<item>
		<id>8</id>
		<name>althochdeutsch</name>
		<abbr>ahd.</abbr>
	</item>
	<item>
		<id>9</id>
		<name>altindisch</name>
		<abbr>ai.</abbr>
	</item>
	<item>
		<id>10</id>
		<name>altirisch</name>
		<abbr>air.</abbr>
	</item>
	<item>
		<id>11</id>
		<name>altisländisch</name>
		<abbr>aisl.</abbr>
	</item>
	<item>
		<id>12</id>
		<name>altlateinisch</name>
		<abbr>alat.</abbr>
	</item>
	<item>
		<id>13</id>
		<name>altniederfränkisch</name>
		<abbr>anfrk.</abbr>
	</item>
	<item>
		<id>14</id>
		<name>altnordisch</name>
		<abbr>an.</abbr>
	</item>
	<item>
		<id>15</id>
		<name>altnorwegisch</name>
		<abbr>anorw.</abbr>
	</item>
	<item>
		<id>16</id>
		<name>altpreußisch</name>
		<abbr>apreuss.</abbr>
	</item>
	<item>
		<id>17</id>
		<name>altsächsisch</name>
		<abbr>asaechs.</abbr>
	</item>
	<item>
		<id>18</id>
		<name>altschwedisch</name>
		<abbr>aschwed.</abbr>
	</item>
	<item>
		<id>19</id>
		<name>angelsächsisch</name>
		<abbr>ags.</abbr>
	</item>
	<item>
		<id>20</id>
		<name>armenisch</name>
		<abbr>armen.</abbr>
	</item>
	<item>
		<id>21</id>
		<name>baltisch</name>
		<abbr>balt.</abbr>
	</item>
	<item>
		<id>22</id>
		<name>bretonisch</name>
		<abbr>bret.</abbr>
	</item>
	<item>
		<id>23</id>
		<name>britisch</name>
		<abbr>brit.</abbr>
	</item>
	<item>
		<id>24</id>
		<name>bulgarisch</name>
		<abbr>bulg.</abbr>
	</item>
	<item>
		<id>25</id>
		<name>burgundisch</name>
		<abbr>burgund.</abbr>
	</item>
	<item>
		<id>26</id>
		<name>kornisch</name>
		<abbr>korn.</abbr>
	</item>
	<item>
		<id>27</id>
		<name>dänisch</name>
		<abbr>daen.</abbr>
	</item>
	<item>
		<id>28</id>
		<name>deutsch</name>
		<abbr>dt.</abbr>
	</item>
	<item>
		<id>29</id>
		<name>englisch</name>
		<abbr>engl.</abbr>
	</item>
	<item>
		<id>30</id>
		<name>estnisch</name>
		<abbr>estn.</abbr>
	</item>
	<item>
		<id>31</id>
		<name>französisch</name>
		<abbr>frz.</abbr>
	</item>
	<item>
		<id>32</id>
		<name>friesisch</name>
		<abbr>frs.</abbr>
	</item>
	<item>
		<id>33</id>
		<name>frühmittelhochdeutsch</name>
		<abbr>fruehmhd.</abbr>
	</item>
	<item>
		<id>34</id>
		<name>frühneuhochdeutsch</name>
		<abbr>fruehnhd.</abbr>
	</item>
	<item>
		<id>35</id>
		<name>gälisch</name>
		<abbr>gael.</abbr>
	</item>
	<item>
		<id>36</id>
		<name>gallisch</name>
		<abbr>gall.</abbr>
	</item>
	<item>
		<id>37</id>
		<name>gotländisch</name>
		<abbr>gotlaend.</abbr>
	</item>
	<item>
		<id>38</id>
		<name>griechisch</name>
		<abbr>griech.</abbr>
	</item>
	<item>
		<id>39</id>
		<name>hebräisch</name>
		<abbr>hebr.</abbr>
	</item>
	<item>
		<id>40</id>
		<name>hethitisch</name>
		<abbr>hethit.</abbr>
	</item>
	<item>
		<id>41</id>
		<name>illyrisch</name>
		<abbr>illyr.</abbr>
	</item>
	<item>
		<id>42</id>
		<name>indogermanisch</name>
		<abbr>idg.</abbr>
	</item>
	<item>
		<id>43</id>
		<name>iranisch</name>
		<abbr>iran.</abbr>
	</item>
	<item>
		<id>44</id>
		<name>irisch</name>
		<abbr>ir.</abbr>
	</item>
	<item>
		<id>45</id>
		<name>isländisch</name>
		<abbr>isl.</abbr>
	</item>
	<item>
		<id>46</id>
		<name>italienisch</name>
		<abbr>ital.</abbr>
	</item>
	<item>
		<id>47</id>
		<name>italisch</name>
	</item>
	<item>
		<id>48</id>
		<name>katalanisch</name>
		<abbr>katalan.</abbr>
	</item>
	<item>
		<id>49</id>
		<name>keltisch</name>
		<abbr>kelt.</abbr>
	</item>
	<item>
		<id>50</id>
		<name>kymrisch</name>
		<abbr>kymr.</abbr>
	</item>
	<item>
		<id>51</id>
		<name>langobardisch</name>
		<abbr>langobard.</abbr>
	</item>
	<item>
		<id>52</id>
		<name>lateinisch</name>
		<abbr>lat.</abbr>
	</item>
	<item>
		<id>53</id>
		<name>lettisch</name>
		<abbr>lett.</abbr>
	</item>
	<item>
		<id>54</id>
		<name>litauisch</name>
		<abbr>lit.</abbr>
	</item>
	<item>
		<id>55</id>
		<name>lydisch</name>
		<abbr>lyd.</abbr>
	</item>
	<item>
		<id>56</id>
		<name>lykisch</name>
		<abbr>lyk.</abbr>
	</item>
	<item>
		<id>57</id>
		<name>mazedonisch</name>
		<abbr>mazedon.</abbr>
	</item>
	<item>
		<id>58</id>
		<name>mittelenglisch</name>
		<abbr>mengl.</abbr>
	</item>
	<item>
		<id>59</id>
		<name>mittelhochdeutsch</name>
		<abbr>mhd.</abbr>
	</item>
	<item>
		<id>60</id>
		<name>mittellateinisch</name>
		<abbr>mlat.</abbr>
	</item>
	<item>
		<id>61</id>
		<name>mittelniederdeutsch</name>
		<abbr>mnd.</abbr>
	</item>
	<item>
		<id>62</id>
		<name>mittelniederländisch</name>
		<abbr>mnl.</abbr>
	</item>
	<item>
		<id>63</id>
		<name>neugriechisch</name>
		<abbr>ngriech.</abbr>
	</item>
	<item>
		<id>64</id>
		<name>neulateinisch</name>
		<abbr>nlat.</abbr>
	</item>
	<item>
		<id>65</id>
		<name>niederländisch</name>
		<abbr>nl.</abbr>
	</item>
	<item>
		<id>66</id>
		<name>nordfriesisch</name>
		<abbr>nordfries.</abbr>
	</item>
	<item>
		<id>67</id>
		<name>norwegisch</name>
		<abbr>norw.</abbr>
	</item>
	<item>
		<id>68</id>
		<name>oskisch</name>
		<abbr>osk.</abbr>
	</item>
	<item>
		<id>69</id>
		<name>ostfriesisch</name>
		<abbr>ostfries.</abbr>
	</item>
	<item>
		<id>70</id>
		<name>pelasgisch</name>
		<abbr>pelasg.</abbr>
	</item>
	<item>
		<id>71</id>
		<name>persisch</name>
		<abbr>pers.</abbr>
	</item>
	<item>
		<id>72</id>
		<name>phrygisch</name>
		<abbr>phryg.</abbr>
	</item>
	<item>
		<id>73</id>
		<name>polnisch</name>
		<abbr>poln.</abbr>
	</item>
	<item>
		<id>74</id>
		<name>portugiesisch</name>
		<abbr>port.</abbr>
	</item>
	<item>
		<id>75</id>
		<name>provenzalisch</name>
		<abbr>prov.</abbr>
	</item>
	<item>
		<id>76</id>
		<name>rätoromanisch</name>
		<abbr>raetorom.</abbr>
	</item>
	<item>
		<id>77</id>
		<name>romanisch</name>
		<abbr>roman.</abbr>
	</item>
	<item>
		<id>78</id>
		<name>rumänisch</name>
		<abbr>rumaen.</abbr>
	</item>
	<item>
		<id>79</id>
		<name>russisch</name>
		<abbr>russ.</abbr>
	</item>
	<item>
		<id>80</id>
		<name>Sanskrit</name>
		<abbr>sanskrit</abbr>
	</item>
	<item>
		<id>81</id>
		<name>sardisch</name>
		<abbr>sard.</abbr>
	</item>
	<item>
		<id>82</id>
		<name>schwedisch</name>
		<abbr>schwed.</abbr>
	</item>
	<item>
		<id>83</id>
		<name>serbokroatisch</name>
		<abbr>serbokr.</abbr>
	</item>
	<item>
		<id>84</id>
		<name>slawisch</name>
		<abbr>slaw.</abbr>
	</item>
	<item>
		<id>85</id>
		<name>slowakisch</name>
		<abbr>slowak.</abbr>
	</item>
	<item>
		<id>86</id>
		<name>sorbisch</name>
		<abbr>sorb.</abbr>
	</item>
	<item>
		<id>87</id>
		<name>spanisch</name>
		<abbr>span.</abbr>
	</item>
	<item>
		<id>88</id>
		<name>tschechisch</name>
		<abbr>tschech.</abbr>
	</item>
	<item>
		<id>89</id>
		<name>thrakisch</name>
		<abbr>thrak.</abbr>
	</item>
	<item>
		<id>90</id>
		<name>tocharisch</name>
		<abbr>tochar.</abbr>
	</item>
	<item>
		<id>91</id>
		<name>umbrisch</name>
		<abbr>umbr.</abbr>
	</item>
	<item>
		<id>92</id>
		<name>urgermanisch</name>
		<abbr>urgerm.</abbr>
	</item>
	<item>
		<id>93</id>
		<name>venetisch</name>
		<abbr>venet.</abbr>
	</item>
	<item>
		<id>94</id>
		<name>vulgärlateinisch</name>
		<abbr>vulglat.</abbr>
	</item>
	<item>
		<id>95</id>
		<name>spätlateinisch</name>
		<abbr>spaetlat.</abbr>
	</item>
	<item>
		<id>96</id>
		<name>ungarisch</name>
		<abbr>ungar.</abbr>
	</item>
</sprachen>
