<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE varietaeten [
	<!ELEMENT varietaeten (item)+>
	<!ELEMENT item (id, name, abbr?)>
	<!ELEMENT id (#PCDATA)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT abbr (#PCDATA)>
]>
<varietaeten>
	<item>
		<id>1</id>
		<name>Amtssprache</name>
	</item>
	<item>
		<id>2</id>
		<name>bairisch</name>
		<abbr>bair.</abbr>
	</item>
	<item>
		<id>3</id>
		<name>Bergmannssprache</name>
	</item>
	<item>
		<id>4</id>
		<name>berlinisch</name>
		<abbr>berlin.</abbr>
	</item>
	<item>
		<id>5</id>
		<name>böhmisch</name>
		<abbr>böhm.</abbr>
	</item>
	<item>
		<id>6</id>
		<name>Druckersprache</name>
	</item>
	<item>
		<id>7</id>
		<name>Fachsprache</name>
	</item>
	<item>
		<id>8</id>
		<name>Fliegersprache</name>
	</item>
	<item>
		<id>9</id>
		<name>fränkisch</name>
		<abbr>fränk.</abbr>
	</item>
	<item>
		<id>10</id>
		<name>friesisch</name>
		<abbr>fries.</abbr>
	</item>
	<item>
		<id>11</id>
		<name>Gaunersprache</name>
	</item>
	<item>
		<id>12</id>
		<name>Gewerbesprache</name>
	</item>
	<item>
		<id>13</id>
		<name>hessisch</name>
		<abbr>hess.</abbr>
	</item>
	<item>
		<id>14</id>
		<name>hochdeutsch</name>
		<abbr>hochd.</abbr>
	</item>
	<item>
		<id>15</id>
		<name>im kommunistischen Sprachgebrauch</name>
		<abbr>kommunist.</abbr>
	</item>
	<item>
		<id>16</id>
		<name>Imkersprache</name>
	</item>
	<item>
		<id>17</id>
		<name>Jägersprache</name>
	</item>
	<item>
		<id>18</id>
		<name>Jugendsprache</name>
	</item>
	<item>
		<id>19</id>
		<name>Kaufmannssprache</name>
	</item>
	<item>
		<id>20</id>
		<name>Kindersprache</name>
	</item>
	<item>
		<id>21</id>
		<name>Kirchensprache</name>
	</item>
	<item>
		<id>22</id>
		<name>landschaftlich</name>
		<abbr>landsch.</abbr>
	</item>
	<item>
		<id>23</id>
		<name>marxistisch</name>
		<abbr>marx.</abbr>
	</item>
	<item>
		<id>24</id>
		<name>mundartlich</name>
		<abbr>mundart.</abbr>
	</item>
	<item>
		<id>25</id>
		<name>norddeutsch</name>
		<abbr>nordd.</abbr>
	</item>
	<item>
		<id>26</id>
		<name>nordostdeutsch</name>
		<abbr>nordostd.</abbr>
	</item>
	<item>
		<id>27</id>
		<name>nordwestdeutsch</name>
		<abbr>nordwestd.</abbr>
	</item>
	<item>
		<id>28</id>
		<name>obersächsisch</name>
		<abbr>obersächs.</abbr>
	</item>
	<item>
		<id>29</id>
		<name>österreichisch</name>
		<abbr>österr.</abbr>
	</item>
	<item>
		<id>30</id>
		<name>ostmitteldeutsch</name>
		<abbr>ostmd.</abbr>
	</item>
	<item>
		<id>31</id>
		<name>ostpreußisch</name>
		<abbr>ostpreuß.</abbr>
	</item>
	<item>
		<id>32</id>
		<name>Parlamentssprache</name>
	</item>
	<item>
		<id>33</id>
		<name>pfälzisch</name>
		<abbr>pfälz.</abbr>
	</item>
	<item>
		<id>34</id>
		<name>preußisch</name>
		<abbr>preuß.</abbr>
	</item>
	<item>
		<id>35</id>
		<name>Rechtssprache</name>
	</item>
	<item>
		<id>36</id>
		<name>rheinisch</name>
		<abbr>rhein.</abbr>
	</item>
	<item>
		<id>37</id>
		<name>sächsisch</name>
		<abbr>sächs.</abbr>
	</item>
	<item>
		<id>38</id>
		<name>schlesisch</name>
		<abbr>schles.</abbr>
	</item>
	<item>
		<id>39</id>
		<name>Schülersprache</name>
	</item>
	<item>
		<id>40</id>
		<name>schwäbisch</name>
		<abbr>schwäb.</abbr>
	</item>
	<item>
		<id>41</id>
		<name>schweizerisch</name>
		<abbr>schweiz.</abbr>
	</item>
	<item>
		<id>42</id>
		<name>Seemannssprache</name>
	</item>
	<item>
		<id>43</id>
		<name>Soldatensprache</name>
	</item>
	<item>
		<id>44</id>
		<name>Studentensprache</name>
	</item>
	<item>
		<id>45</id>
		<name>süddeutsch</name>
		<abbr>südd.</abbr>
	</item>
	<item>
		<id>46</id>
		<name>südwestdeutsch</name>
		<abbr>südwestd.</abbr>
	</item>
	<item>
		<id>47</id>
		<name>thüringisch</name>
		<abbr>thüring.</abbr>
	</item>
	<item>
		<id>48</id>
		<name>Umgangssprache</name>
	</item>
	<item>
		<id>49</id>
		<name>Werbesprache</name>
	</item>
	<item>
		<id>50</id>
		<name>westfälisch</name>
		<abbr>westfäl.</abbr>
	</item>
	<item>
		<id>51</id>
		<name>westmitteldeutsch</name>
		<abbr>westmd.</abbr>
	</item>
	<item>
		<id>52</id>
		<name>wienerisch</name>
		<abbr>wiener.</abbr>
	</item>
	<item>
		<id>53</id>
		<name>Winzersprache</name>
	</item>
	<item>
		<id>54</id>
		<name>Zigeunersprache</name>
	</item>
</varietaeten>
